/// Flutter icons AmologicIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AmologicIcons
///      fonts:
///       - asset: fonts/AmologicIcons.ttf
///
import 'package:flutter/widgets.dart';

class AmologicIcons {
  AmologicIcons._();

  static const _kFontFam = 'AmologicIcons';
  static const String? _kFontPkg = null;

  static const IconData healthypet = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dog = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cat = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chats = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorites = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
